theme: jekyll-theme-tactile
#Google Analytics
google_analytics: UA-165263820-1
url: https://hokenh.github.com/monstres
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
